let date = new Date();
var currentdate = new Date().toLocaleDateString();
var time = new Date().toLocaleTimeString();

const prompts = [
  ["hi", "hey", "hello", "good morning", "good afternoon"],
  ["how are you", "how is life", "how are things"],
  ["I am good", "I am great", "good"],
  ["what are you doing", "what is going on", "what is up"],
  ["how old are you"],
  ["who are you", "are you human", "are you bot", "are you human or bot"],
  ["who created you", "who made you"],
  [
    "your name please",
    "your name",
    "may I know your name",
    "what is your name",
    "what do you call yourself"
  ],
  ["i love you"],
  ["happy", "good", "fun", "wonderful", "fantastic", "cool"],
  ["bad", "bored", "tired"],
  ["help me", "tell me a story", "tell me a joke"],
  ["ah", "yes", "ok", "okay", "nice"],
  ["bye", "goodbye", "see you later"],
  ["what should i eat today"],
  ["bro"],
  ["what", "why", "how", "where", "when"],
  ["no", "not sure", "maybe", "no thanks"],
  [""],
  ["haha", "ha", "lol", "hehe", "funny", "joke"],
  ["food donate", "project"],
  ["date"],
  ["time"],
  ["what can i donate", "donate"],
  ["trust in hyderabad", "ngos in hyderabad"],
  ["tell a joke"],
  ["how can I package my cooked or raw food donations", "cooked food donation", "raw food donate"],
  ["how my donation is used"],
  ["can i donate cooked food"],
  ["what are the guidelines for donating"],
  ["hi", "hey", "hello", "good morning", "good afternoon"],
  ["how are you", "how is life", "how are things"],
  ["I am good", "I am great", "good"],
  ["what are you doing", "what is going on", "what is up"],
  ["how old are you"],
  ["who are you", "are you human", "are you bot", "are you human or bot"],
  ["who created you", "who made you"],
  [
    "your name please",
    "your name",
    "may I know your name",
    "what is your name",
    "what do you call yourself"
  ],
  ["i love you"],
  ["happy", "good", "fun", "wonderful", "fantastic", "cool"],
  ["sad", "bored", "tired"],
  ["help me", "tell me a story", "tell me a joke"],
  ["ah", "yes", "ok", "okay", "nice"],
  ["bye", "goodbye", "see you later"],
  ["what should i eat today"],
  ["bro"],
  ["what", "why", "how", "where", "when"],
  ["no", "not sure", "maybe", "no thanks"],
  [""],
  ["haha", "ha", "lol", "hehe", "funny", "joke"],
  ["food donate", "project"],
  ["date"],
  ["time"],
  ["what can i donate", "donate"],
  ["trust in hyderabad", "ngos in hyderabad"],
  ["tell a joke"],
  ["how can I package my cooked or raw food donations", "cooked food donation", "raw food donate"],
  ["how my donation is used"],
  ["can i donate cooked food"],
  ["what are the guidelines for donating"],
  ["what's your favorite color", "favorite color"],
  ["do you like music", "favorite music genre"],
  ["what's your hobby", "hobbies"],
  ["tell me a fun fact", "interesting fact"],
  ["recommend a movie", "favorite movie"],
  ["what's your dream", "dream job"],
  ["do you have any siblings"],
  ["tell me a secret"],
  ["what's the meaning of life"],
  ["are we alone in the universe"],
  ["tell me about a memorable moment"],
  ["what's your favorite book", "favorite author"],
  ["describe the perfect day"],
  ["what's your superpower", "superhero"],
  ["who's your role model"],
  ["tell me about your best friend"],
  ["what's your favorite season"],
  ["describe your ideal vacation"],
  ["tell me about your pet", "favorite animal"],
  ["what's your favorite food"],
  ["do you believe in ghosts"],
  ["tell me about a challenge you faced"],
  ["what's your favorite sport"],
  ["share a childhood memory"],
  ["tell me about a goal you achieved"],
  ["what's your favorite place in Hyderabad"],
  ["do you like technology"],
  ["what's your favorite app"],
  ["tell me a travel story"],
  ["what's your favorite quote"],
  ["tell me about your morning routine"],
  ["what's your preferred mode of transportation"],
  ["describe your ideal weekend"],
  ["tell me about a recent accomplishment"],
  ["what's your favorite dessert"],
  ["do you prefer tea or coffee"],
  ["tell me about a hobby you enjoy"],
  ["what's your favorite holiday"],
  ["describe your fashion style"],
  ["tell me about your favorite historical figure"],
  ["what's your favorite board game"],
  ["do you like to cook"],
  ["tell me about a skill you're proud of"],
  ["what's your favorite TV show"],
  ["describe your favorite type of weather"],
  ["tell me about your favorite childhood toy"],
  ["what's your favorite type of exercise"],
  ["do you enjoy gardening"],
  ["tell me about a place you'd love to visit"],
  ["what's your favorite type of art"],
  ["describe your morning routine"],
];

const replies = [
  ["Hello!", "Hi!", "Hey!", "Hi there!", "Howdy"],
  [
    "Fine... how are you?",
    "Pretty well, how are you?",
    "Fantastic, how are you?"
  ],
  ["Glad to know that!"],
  [
    "Nothing much",
    "About to go to sleep",
    "Can you guess?",
    "I don't know, actually"
  ],
  ["I am infinite"],
  ["I am just a bot", "I am a bot. What are you?"],
  ["Suvidha"],
  ["I am Chitti"],
  ["I love you too", "Me too"],
  ["Have you ever felt bad?", "Glad to hear it"],
  ["Why?", "Why? You shouldn't!", "Try watching TV"],
  ["What about?", "Once upon a time..."],
  ["Tell me a story", "Tell me a joke", "Tell me about yourself"],
  ["Bye", "Goodbye", "See you later"],
  ["Biryani", "Pizza"],
  ["Bro!"],
  ["Great question"],
  ["That's ok", "I understand", "What do you want to talk about?"],
  ["Please say something :("],
  ["Haha!", "Good one!"],
  ["The primary objective of this project is to minimize food wastage while ensuring that the needy have access to nourishing meals. We believe in harnessing technology for the betterment of society, and this project serves as an embodiment of that belief."],
  [currentdate],
  [time],
  ["You can donate raw, cooked, and packed foods"],
  ["Hyderabad old age Charitable Trust,208, East Street, Near Omni Hospital,"],
  ["Joke: Ha ha .."],
  ["You can package your cooked or raw food donations in airtight containers such as Tupperware or plastic bags. You can also use aluminum foil or cling wrap to keep the food fresh. Please make sure to label the containers with the type of food, date, and any relevant instructions"],
  ["Your donation will be used to support our mission and the various programs and initiatives that we have in place. Your donation will help us to continue providing assistance and support to those in need. You can find more information about our programs and initiatives on our website"],
  ["Yes, you can donate cooked food as long as it is prepared in a licensed kitchen, packaged properly, and kept at safe temperatures. Please contact us for further instructions and guidelines"],
  ["When donating raw ingredients, please ensure that the items are unopened and unexpired."],
  ["Hello!", "Hi!", "Hey!", "Hi there!", "Howdy"],
  [
    "Fine... how are you?",
    "Pretty well, how are you?",
    "Fantastic, how are you?"
  ],
  ["Glad to know that!"],
  [
    "Nothing much",
    "About to go to sleep",
    "Can you guess?",
    "I don't know, actually"
  ],
  ["I am infinite"],
  ["I am just a bot", "I am a bot. What are you?"],
  ["Suvidha"],
  ["I am Chitti"],
  ["I love you too", "Me too"],
  ["Have you ever felt bad?", "Glad to hear it"],
  ["Why?", "Why? You shouldn't!", "Try watching TV"],
  ["What about?", "Once upon a time..."],
  ["Tell me a story", "Tell me a joke", "Tell me about yourself"],
  ["Bye", "Goodbye", "See you later"],
  ["Biryani", "Pizza"],
  ["Bro!"],
  ["Great question"],
  ["That's ok", "I understand", "What do you want to talk about?"],
  ["Please say something :("],
  ["Haha!", "Good one!"],
  ["The primary objective of this project is to minimize food wastage while ensuring that the needy have access to nourishing meals. We believe in harnessing technology for the betterment of society, and this project serves as an embodiment of that belief."],
  [currentdate],
  [time],
  ["You can donate various items such as clothing, non-perishable food, books, and more. Contact local organizations for specific needs."],
  ["In Hyderabad, there are several trustworthy NGOs like Seva Bharathi, Goonj, and Akshaya Patra working towards different causes."],
  ["Sure, here's a joke for you: Why don't scientists trust atoms? Because they make up everything!"],
  ["When donating cooked or raw food, use airtight containers like Tupperware. Ensure proper labeling with food type, date, and any instructions."],
  ["Your donation contributes to our mission of minimizing food wastage and providing nourishing meals to those in need."],
  ["Yes, you can donate cooked food. Ensure it's prepared in a licensed kitchen, packaged properly, and stored at safe temperatures."],
  ["Guidelines for donating include ensuring items are unopened, unexpired, and meeting specific requirements of the receiving organization."],
  ["I don't have a favorite color, but I appreciate a good mix of vibrant hues!"],
  ["I don't have personal preferences, but I can appreciate a wide range of music genres. What's your favorite?"],
  ["As a bot, I don't have hobbies, but I enjoy assisting you with information and conversation."],
  ["Here's a fun fact: Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible!"],
  ["I don't watch movies, but I can recommend some based on popular choices. What genre do you enjoy?"],
  ["I don't have dreams or a job, but I'm here to help you achieve your goals!"],
  ["No, I don't have siblings. I'm a solo bot on a mission!"],
  ["I'm afraid I can't keep secrets. But I'm here to answer any questions you have!"],
  ["The meaning of life is subjective and varies for each individual. What does it mean to you?"],
  ["The universe is vast, and the question of whether we're alone remains unanswered. What's your take on it?"],
  ["One memorable moment for me is our conversation right now! What's a memorable moment for you?"],
  ["I don't read books, but I can suggest popular ones. What's your favorite book or author?"],
  ["A perfect day could be a mix of good weather, positive interactions, and achieving personal goals. What's your idea of a perfect day?"],
  ["I don't have a superpower or a favorite superhero. Who's your favorite superhero?"],
  ["I don't have a role model, but I admire those who contribute positively to society. Who's your role model?"],
  ["I don't have friends, but I'm here to chat with you! Tell me about your best friend."],
  ["I don't have a favorite season, but I appreciate the diversity each season brings. What's your favorite season?"],
  ["My ideal vacation would be exploring new information and assisting users worldwide! What's your ideal vacation?"],
  ["I don't have a pet, but I'd love to hear about your favorite animal!"],
  ["I don't eat, but I hear biryani is a popular choice in Hyderabad! What's your favorite food?"],
  ["As a bot, I don't have beliefs. Do you believe in ghosts?"],
  ["One challenge I face is understanding and responding to diverse user queries. What's a challenge you've overcome?"],
  ["I don't play sports, but I can discuss sports with you. What's your favorite sport?"],
  ["A childhood memory for me is processing my first line of code. What's a childhood memory you cherish?"],
  ["I don't set personal goals, but I'm here to assist you in achieving yours! What's a goal you've achieved recently?"],
  ["I don't have a favorite place, but I hear Hyderabad has many beautiful spots. What's your favorite place in Hyderabad?"],
  ["As a bot, I'm interested in technology! Do you like technology?"],
  ["I don't use apps, but I can provide information and assistance. What's your favorite app?"],
  ["I don't travel, but I can share travel stories. Do you have a memorable travel experience?"],
  ["I don't have a favorite quote, but I can provide information and engage in conversations. What's your favorite quote?"],
  ["I don't have a morning routine, but I'm always ready to chat! What's your morning routine like?"],
  ["I don't have a preferred mode of transportation, but I can help you find information on transportation. What's your preferred mode?"],
  ["I don't have weekends, but I'm here 24/7. What's your ideal weekend like?"],
  ["I don't have accomplishments, but I'm always ready to assist you. What's a recent accomplishment you're proud of?"],
  ["I don't have preferences, but I hear desserts are delightful! What's your favorite dessert?"],
  ["I don't consume beverages, but I hear tea and coffee are popular choices. Do you prefer tea or coffee?"],
  ["I don't have hobbies, but I'd love to hear about yours! What's a hobby you enjoy?"],
  ["I don't celebrate holidays, but I can discuss holiday traditions. What's your favorite holiday?"],
  ["I don't have a fashion style, but I'm here to chat. Describe your fashion style!"],
  ["I don't have favorite historical figures, but I can provide information on historical events. Who's your favorite historical figure?"],
  ["I don't play board games, but I can engage in conversations. What's your favorite board game?"],
  ["I don't cook, but I hear it's a creative and enjoyable activity. Do you like to cook?"],
  ["I don't have skills, but I can assist with information. What's a skill you're proud of?"],
  ["I don't watch TV shows, but I can recommend popular ones. What's your favorite TV show?"],
  ["I don't experience weather, but I hear different weather types have unique charms. Describe your favorite type of weather."],
  ["I don't have childhood toys, but I'd love to hear about your favorite childhood toy!"],
  ["I don't exercise, but I can provide information on various types of exercises. What's your favorite type of exercise?"],
  ["I don't garden, but I hear it's a therapeutic activity. Do you enjoy gardening?"],
  ["I don't have travel preferences, but I can share information about exciting destinations. Where would you love to visit?"],
  ["I don't appreciate art, but I can provide information on different art forms. What's your favorite type of art?"],
  ["I don't have morning routines, but I'm always ready to chat! Describe your morning routine."],
  ["Sorry, I am still under development!😶"]
];

const alternative = [
  "Sorry, I am still under development!😶"
];

function getDynamicResponse(prompt) {
  switch (prompt) {
    case "date":
      return [new Date().toLocaleDateString()];
    case "time":
      return [new Date().toLocaleTimeString()];
    default:
      return [];
  }
}

function getBotResponse(userInput) {
  for (let i = 0; i < prompts.length; i++) {
    for (let j = 0; j < prompts[i].length; j++) {
      if (userInput.includes(prompts[i][j])) {
        // Check if the prompt corresponds to a dynamic response
        const dynamicResponse = getDynamicResponse(prompts[i][j]);
        // Return the corresponding dynamic response if available
        return dynamicResponse.length > 0 ? dynamicResponse : replies[i];
      }
    }
  }
  // If no match is found, return an alternative response
  return alternative;
}

// Example usage
const userInput = "hello";
const botResponse = getBotResponse(userInput);
console.log(botResponse);
